### PR TITLE
Use parallel + hostinfo to get IP address when deploying.

### PR DESCRIPTION
**Pull request by PeterJohnson**
This avoids multiple DNS/mDNS lookups and performs the lookups in parallel.

Also fix up a couple of adminUsername / adminPassword cases.

### CODE REVIEW

**Comment by PeterJohnson** [comment]
@Kevin-OConnor

**Comment by sciencewhiz** [comment]
I haven't yet duplicated the condition where isReachable provided false trues to make sure this works. I did test that in an fast mDNS environment, and when no roboRIO is on the network, the time is about the same as with previous. I plan to do more testing in various network conditions this weekend.

**Review by ThadHouse — APPROVED** [review]

**Comment by 333fred** [comment]
@sciencewhiz, you might be able to use the hosts file to make roborio-number-frc.local resolve to an unreachable address.

**Comment by PeterJohnson** [comment]
My local machine had the false positive isReachable's, so I've at least tested that myself.

**Pull request merged**
