### PR TITLE
Fixes installation on Eclipse Neon and debugging with shared libraries

### LINKED ISSUE #7: C++ plugin neither builds nor installs with Eclipse Neon
See https://www.chiefdelphi.com/forums/showthread.php?t=149135.

### PR DESCRIPTION
**Pull request by Kevin-OConnor**
Closes #7

### CODE REVIEW

**Comment by Kevin-OConnor** [comment]
I don't recall changing the indent on that large chunk of code, but it looks correct in my editor now and git status says it's up to date. Someone can let me know if it looks off.

**Comment by PeterJohnson** [comment]
Yeah, it looks like tabs vs spaces change on a number of lines.

**Comment by Kevin-OConnor** [comment]
The rest of the plugin files are all tabs so I set for tabs, that may have been what did some of it. It looks like the indent level was wrong on some things as well which I must have fixed and forgotten about.

**Comment by Kevin-OConnor** [comment]
The plugin files are in desperate need of formatting

**Review by PeterJohnson — APPROVED** [review]

**Pull request merged**
