### PR TITLE
Updates maven locations to 2018

### PR DESCRIPTION
**Pull request by ThadHouse**

### CODE REVIEW

**Comment by ThadHouse** [comment]
@frcjenkins  retest this please

**Comment by sciencewhiz** [comment]
Fixes #120

**Comment by sciencewhiz** [comment]
On old projects, the java build path references both NetworkTables.jar and ntcore.jar. NetworkTables.jar is old and can't be found which causes eclipse to mark that there's a problem with the project. The project still compiles.

**Comment by sciencewhiz** [comment]
wpiutil-sources.jar doesn't get installed

**Comment by ThadHouse** [comment]
@sciencewhiz I fixed the wpiutil sources, but the NetworkTables.jar is going to be a longer fix. @PeterJohnson We can still merge this now, and create an issue for that if we want to make a beta, or I can figure out the fix.

**Comment by PeterJohnson** [comment]
Regarding old projects, I think we had a similar problem last year with old projects, but I forget what we did to address it (if anything).

**Comment by ThadHouse** [comment]
Last year was adding new items this is removing old items so we are not set up for it yet

**Comment by sciencewhiz** [comment]
An easy way to solve the classpath variable issue is to not rename the variable. Keep the name networktables and point to ntcore.jar.
I tried [removeClasspathVariable](http://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2FJavaCore.html&anchor=removeClasspathVariable-java.lang.String-org.eclipse.core.runtime.IProgressMonitor-), but it didn't seem to work

**Comment by ThadHouse** [comment]
Oh I didn't realize I could rename the jar and keep the variable the same. I'll do that.

**Comment by ThadHouse** [comment]
Ok that should now be fixed.

**Review by AustinShalit — DISMISSED** [review]
@bradamiller and I tested this with Java programs and it works as expected

**Comment by ThadHouse** [comment]
Did either of you test c++? I would like someone other then me to test cpp before merging

**Comment by PeterJohnson** [comment]
C++ does not work unless Java is deployed first, as the C++ FRCUserProgram links against libopencv_java320.so but this file is not copied to the robot by the C++ deploy.

**Comment by ThadHouse** [comment]
@PeterJohnson I fixed this by having the C++ libraries deploy the JNI file. I forgot that was a side effect of removing the link scripts and the new way gradle does linking to native libraries. Its a small file, so not a big deal.

**Review by PeterJohnson — APPROVED** [review]

**Pull request merged**
