### PR TITLE
Add examples of how to use IterativeRobot in SampleRobot

### PR DESCRIPTION
**Pull request by AustinShalit**
This PR should be merged and then https://github.com/wpilibsuite/allwpilib/pull/472 should be good to go.

### CODE REVIEW

**Comment by PeterJohnson** [comment]
Do these code snippets appear as code in the generated docs, or is some markup needed?

**Comment by ArchdukeTim** [comment]
Shouldn't this code be in the IterativeRobot template as well? It's weird to show driving in auto for SampleRobot, but in Iterative it just has a basic framework that doesn't actually do anything

**Comment by AustinShalit** [comment]
@PeterJohnson 
These files do not have have generated documentation.  I could format it so it would look like code in generated documentation but I think that makes it harder to read in the file itself.

@Twinters007 
Interesting thought.  Right now this code is the same as the "Getting Started" template.

**Comment by PeterJohnson** [comment]
In looking at this again, we should make it clearer here what we're trying to say / warn about before jumping into the example code.  Something like "SampleRobot is deprecated; we recommend you use a different template such as IterativeRobot.  The main downside of using SampleRobot is that it's easy for your autonomous code to keep running even after the autonomous period has ended, which will prevent your robot from being driven in teleoperated mode!  The most common thing that you may want to do is have a timed sequence of events--rather than doing drive; sleep; drive in the SampleRobot template, a timed sequence can be accomplished in the IterativeRobot template by..."

**Comment by PeterJohnson** [comment]
Please resubmit against allwpilib, as examples have moved there.

**Pull request closed without merging**
