### PR TITLE
Java debug fix. Added missing libs.deployDir

### PR DESCRIPTION
**Pull request by sciencewhiz**
Incorporates and supersedes #91. Adds missing libs.deployDir to debug-deploy. Updates debug-deploy to be like deploy target

### CODE REVIEW

**Comment by sciencewhiz** [comment]
@gerth2 This fixes java debugging for me. Does it fix your problems as well?

**Comment by gerth2** [comment]
Hmmm possibly? Will have test board access tomorrow morning, will check then! 

I think I still had issues with the post-deploy connection between the Eclipse debugger and the remote JVM on the RIO starting up, but I haven't dug into that much more yet... I presume some of that behavior defined is within the the definition of the WPIlib eclipse plugin, which hasn't been changed in our series of updates yet. Some of it may also be my eclipse settings....I guess I still have much to actually look into </stream_of_consciousness>

**Comment by gerth2** [comment]
Double checked - this does not 100% fix my issues. Although the ant build goes through without errors, Eclipse cannot establish the remote debug connection to the RIO. The same issue is present from at least one other user. (see https://www.chiefdelphi.com/forums/showthread.php?p=1631965#post1631965)... Will do some more investigation soon....

**Comment by Kevin-OConnor** [comment]
Do you know which option of resolving the roboRIO the ant deploy is using when you are seeing the debugger fail to connect? The debugger will only connect using the mDNS address right now. The ant deploy has many more resolution options in it.

**Comment by gerth2** [comment]
Per the console output from manually running "ant debug-deploy", yes I am getting the debug and deploy to find the robot over mdns:

    get-target-ip:
         [echo] Trying Target: roboRIO-1736-FRC.local
         [echo] roboRIO found via mDNS

**Comment by gerth2** [comment]
More debugging: It would seem that if I manually run the ant debug-deploy build, and then go to eclipse to run the debug build from the GUI, the debugger connects at the same time as the ant build starts (from eclipse) - is there any chance the eclipse debug connect is not waiting for the ant build to finish before it attempts to connect to the RIO with a debugger?

**Comment by PeterJohnson** [comment]
Please open a separate issue for the other debug issues.

**Comment by gerth2** [comment]
Sounds good. I definitely concur the change from this PR is needed. I will open separate issue. Thanks folks!

**Pull request merged**
